"""archive tables

Revision ID: 8b75e1eb30a3
Revises: 
Created: 2026-09-04 20:26:17.947923
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8b75e1eb30a3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('company_name', sa.String(length=160), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('expected_close', sa.Date(), nullable=True),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('origin', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archived_deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archived_deals_closed_on'), ['closed_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_archived_deals_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_archived_deals_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_archived_deals_stage'), ['stage'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archived_deals_stage'))
        batch_op.drop_index(batch_op.f('ix_archived_deals_owner'))
        batch_op.drop_index(batch_op.f('ix_archived_deals_name'))
        batch_op.drop_index(batch_op.f('ix_archived_deals_closed_on'))

    op.drop_table('archived_deals')
    # ### end Alembic commands ###
