"""Alembic's entry point.

Two things are wired up here that a generated env.py does not do. The database
URL comes from ``connections.yaml`` rather than ``alembic.ini``, so there is
one place to configure it. The metadata comes from ``app.schema`` plus the
tables the enabled modules declare, so
``alembic revision --autogenerate`` compares against the declared tables.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlalchemy.pool import NullPool

from app.core.connections import ConnectionRegistry
from app.core.modules import select as select_modules
from app.schema import metadata
from app.settings import get_settings

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

#: What autogenerate compares the database against.
# Importing the enabled modules attaches their tables to the same metadata, so
# an autogenerated migration covers exactly the modules this deployment runs.
# Change CRM_MODULES and the next `crm make-migration` reflects it.
select_modules(enabled=get_settings().modules or None)

target_metadata = metadata


def database_url() -> str:
    """The URL of the main database, from the application's own configuration."""
    settings = get_settings()
    registry = ConnectionRegistry.from_file(settings.connections_path)
    name = config.get_main_option("crm_connection", "db.main")
    return str(registry.spec(name).option("url", required=True))


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it.

    Used by ``alembic upgrade head --sql`` to produce a script for a DBA who
    would rather apply it themselves.
    """
    context.configure(
        url=database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Type changes are detected too; without this a column changing from
        # String(60) to String(200) passes unnoticed.
        compare_type=True,
        # SQLite cannot ALTER most things, so alembic rebuilds the table
        # instead. Harmless elsewhere, and it means one migration works on
        # both SQLite and PostgreSQL.
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = database_url()

    engine = async_engine_from_config(section, prefix="sqlalchemy.", poolclass=NullPool)
    async with engine.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await engine.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
