"""demo tables

Tables belonging to the optional ``demo_crm`` and ``demo_sales`` modules.

Both halves are guarded: the enabled modules attach their tables to the shared
metadata, so if this deployment does not run the demo modules the tables are
absent from it and this revision does nothing. That keeps one linear history
across deployments that enable different modules, at the cost of a guard per
module-owned revision. A project with many such modules would instead give
each one its own Alembic ``version_locations`` branch.


Revision ID: 274f60e4dcfb
Revises: 2f93cea708e0
Created: 2026-09-04 14:51:31.759490
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.schema import metadata

revision: str = '274f60e4dcfb'
down_revision: str | None = '2f93cea708e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Present only when the modules that declare them are enabled.
DEMO_TABLES = ("companies", "contacts", "deals", "activities")


def _enabled() -> bool:
    return all(name in metadata.tables for name in DEMO_TABLES)


def upgrade() -> None:
    if not _enabled():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=60), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_owner'), ['owner'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_contacted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('attachment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_status'), ['status'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('expected_close', sa.Date(), nullable=True),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_stage'), ['stage'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_done'), ['done'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_due_on'), ['due_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_owner'), ['owner'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    if not _enabled():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_owner'))
        batch_op.drop_index(batch_op.f('ix_activities_kind'))
        batch_op.drop_index(batch_op.f('ix_activities_due_on'))
        batch_op.drop_index(batch_op.f('ix_activities_done'))
        batch_op.drop_index(batch_op.f('ix_activities_deal_id'))
        batch_op.drop_index(batch_op.f('ix_activities_contact_id'))

    op.drop_table('activities')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_stage'))
        batch_op.drop_index(batch_op.f('ix_deals_owner'))
        batch_op.drop_index(batch_op.f('ix_deals_name'))
        batch_op.drop_index(batch_op.f('ix_deals_contact_id'))
        batch_op.drop_index(batch_op.f('ix_deals_company_id'))

    op.drop_table('deals')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_status'))
        batch_op.drop_index(batch_op.f('ix_contacts_owner'))
        batch_op.drop_index(batch_op.f('ix_contacts_name'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_owner'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_industry'))

    op.drop_table('companies')
    # ### end Alembic commands ###
