"""password state

Columns supporting password change, admin reset and lockout. Only meaningful
where a provider that holds passwords is configured; under SSO they stay null,
which is the honest representation of "there is no password here".

The two NOT NULL columns carry a server_default, because an existing table with
rows in it has no other way to fill them.

Revision ID: e71bca3ad6a9
Revises: 274f60e4dcfb
Created: 2026-09-04 15:18:18.244643
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e71bca3ad6a9'
down_revision: str | None = '274f60e4dcfb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column('must_change_password', sa.Boolean(), nullable=False,
                      server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('failed_logins', sa.Integer(), nullable=False,
                      server_default=sa.text('0'))
        )
        batch_op.add_column(sa.Column('last_failed_login', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('last_failed_login')
        batch_op.drop_column('failed_logins')
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('password_changed_at')

    # ### end Alembic commands ###
